In [1]:
import pandas as pd

In [3]:
## read from existing results :
negation = pd.read_csv("Task13-P-U-Negation_train.csv",sep=',')
print(negation.columns)
negation

/tmp/ipykernel_1622476/991070602.py:2: DtypeWarning: Columns (21,40) have mixed types. Specify dtype option on import or set low_memory=False.
  negation = pd.read_csv("Task13-P-U-Negation_train.csv",sep=',')

Index(['Question_Id', 'Context', 'Original_Question', 'Original_Answer',
       'Modified_Question', 'O-Q model2 answer span', 'O-Q model2 start',
       'O-Q model2 end', 'O-Q model2 score', 'O-Q model4 answer span',
       'O-Q model4 start', 'O-Q model4 end', 'O-Q model4 score',
       'O-Q electra answer span', 'O-Q electra start', 'O-Q electra end',
       'O-Q electra score', 'O-Q roberta answer span', 'O-Q roberta start',
       'O-Q roberta end', 'O-Q roberta score', 'O-Q sgnet answer span',
       'O-Q retro answer span', 'P-U model2 answer span', 'P-U model2 start',
       'P-U model2 end', 'P-U model2 score', 'P-U model4 answer span',
       'P-U model4 start', 'P-U model4 end', 'P-U model4 score',
       'P-U electra answer span', 'P-U electra start', 'P-U electra end',
       'P-U electra score', 'P-U roberta answer span', 'P-U roberta start',
       'P-U roberta end', 'P-U roberta score', 'P-U retro answer span',
       'P-U SgNet answer span'],
      dtype='object')

,Question_Id,Context,Original_Question,Original_Answer,Modified_Question,O-Q model2 answer span,O-Q model2 start,O-Q model2 end,O-Q model2 score,O-Q model4 answer span,...,P-U electra answer span,P-U electra start,P-U electra end,P-U electra score,P-U roberta answer span,P-U roberta start,P-U roberta end,P-U roberta score,P-U retro answer span,P-U SgNet answer span
0,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When didn't Beyonce start becoming popular?,late 1990s,275,286,0.636688,late 1990s,...,hiatus saw the release of Beyoncé's debut albu...,456,524,3.663901e-12,4,74,75,2.375909e-09,<No Answer>. The question is not answerable ac...,the late 1990s as
1,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce not start becoming popular?,late 1990s,275,286,0.636688,late 1990s,...,"release of Beyoncé's debut album, Dangerously ...",471,530,3.835370e-11,4,74,75,1.432447e-09,<No Answer>. The question is not answerable ac...,the late 1990s as
2,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce start not becoming popular?,late 1990s,275,286,0.636688,late 1990s,...,2003,526,530,5.543973e-05,2003,526,530,2.668854e-09,<No Answer>. The question is not answerable ac...,the late 1990s as
3,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas didn't Beyonce compete in when she ...,singing and dancing,206,226,0.836062,singing and dancing,...,dancing,219,226,7.576573e-12,Beyoncé Giselle Knowles-Carter,0,30,2.841676e-09,<No Answer>. The question is not answerable ac...,NaN
4,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas did Beyonce compete in when she was...,singing and dancing,206,226,0.836062,singing and dancing,...,singing and dancing,207,226,2.723598e-07,singing and dancing competitions,207,239,1.565185e-06,<No Answer>. The question is not answerable ac...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162180,5735d259012e2f140011a09f,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,Minsk,With what Belorussian city doesn't Kathmandu h...,Minsk,475,481,0.972188,Minsk,...,Minsk,476,481,3.207862e-09,Minsk,476,481,5.784440e-09,<No Answer>. The question is not answerable ac...,NaN
162181,5735d259012e2f140011a09f,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,Minsk,With what Belorussian city does Kathmandu not ...,Minsk,475,481,0.972188,Minsk,...,Minsk,476,481,1.300888e-08,Minsk,476,481,1.215596e-07,<No Answer>. The question is not answerable ac...,NaN
162182,5735d259012e2f140011a0a0,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,1975,In what year didn't Kathmandu create its initi...,1975,198,203,0.996814,1975,...,1975,199,203,3.486395e-12,1975,199,203,8.635733e-11,<No Answer>. The question is not answerable ac...,NaN
162183,5735d259012e2f140011a0a0,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,1975,In what year did Kathmandu not create its init...,1975,198,203,0.996814,1975,...,1975,199,203,9.288781e-13,1975,199,203,1.607741e-10,<No Answer>. The question is not answerable ac...,NaN
162184,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,What isn't KMC an initialism of?,Kathmandu Metropolitan City,0,27,0.949815,Kathmandu,...,IRC,135,138,3.328238e-14,Motsumoto City of Japan,350,373,5.829913e-11,<No Answer>. The question is not answerable ac...,empty

# Cleaning Model's answer

In [4]:
import re

def preprocess_text2(text):
    if not pd.isna(text): 
        # Remove special characters from the left side
        text = re.sub(r'^\W+', '', text)

        # Remove special characters from the right side
        text = re.sub(r'\W+$', '', text)
        return text
    else: ## it's nan
        return ''
    
    
def preprocess_text(text):
    if not pd.isna(text): 
        return text
    else: ## it's nan
        return ''

text = "(2003)!,"
processed_text = preprocess_text(text)
print(processed_text)

(2003)!,

In [5]:
### Cleaning the result of models
import ast
Cln_orgQ_model2 = []
Cln_orgQ_model4 = []
Cln_orgQ_electra = []
Cln_orgQ_roberta = []
Cln_orgQ_sgnet = []
Cln_orgQ_retro = []

Cln_potUQ_model2 = []
Cln_potUQ_model4 = []
Cln_potUQ_electra = []
Cln_potUQ_roberta = []
Cln_potUQ_sgnet = []
Cln_potUQ_retro = []

for index, row in negation.iterrows():
    if index % 100000 == 0:
        print(index)
    
    original_question_model2 = row['O-Q model2 answer span']
    original_question_model4 = row['O-Q model4 answer span']
    original_question_electra = row['O-Q electra answer span']
    original_question_roberta = row['O-Q roberta answer span']
    original_question_sgnet = row['O-Q sgnet answer span']
    original_question_retro = row['O-Q retro answer span']
    
    potentialU_question_model2 = row['P-U model2 answer span']
    potentialU_question_model4 = row['P-U model4 answer span']
    potentialU_question_electra = row['P-U electra answer span']
    potentialU_question_roberta = row['P-U roberta answer span']
    potentialU_question_sgnet = row['P-U SgNet answer span']
    potentialU_question_retro = row['P-U retro answer span']
    
    
    Cln_orgQ_model2.append(preprocess_text(original_question_model2))
    Cln_orgQ_model4.append(preprocess_text(original_question_model4))
    Cln_orgQ_electra.append(preprocess_text(original_question_electra))
    Cln_orgQ_roberta.append(preprocess_text(original_question_roberta))
    Cln_orgQ_sgnet.append(preprocess_text(original_question_sgnet))
    Cln_orgQ_retro.append(preprocess_text(original_question_retro))
    
    Cln_potUQ_model2.append(preprocess_text(potentialU_question_model2))
    Cln_potUQ_model4.append(preprocess_text(potentialU_question_model4))
    Cln_potUQ_electra.append(preprocess_text(potentialU_question_electra))
    Cln_potUQ_roberta.append(preprocess_text(potentialU_question_roberta))
    Cln_potUQ_sgnet.append(preprocess_text(potentialU_question_sgnet))
    Cln_potUQ_retro.append(preprocess_text(potentialU_question_retro))

    
      
negation['Cln_orgQ_model2'] = Cln_orgQ_model2
negation['Cln_orgQ_model4'] = Cln_orgQ_model4
negation['Cln_orgQ_electra'] = Cln_orgQ_electra
negation['Cln_orgQ_roberta'] = Cln_orgQ_roberta
negation['Cln_orgQ_sgnet'] = Cln_orgQ_sgnet
negation['Cln_orgQ_retro'] = Cln_orgQ_retro


negation['Cln_potUQ_model2'] = Cln_potUQ_model2
negation['Cln_potUQ_model4'] = Cln_potUQ_model4
negation['Cln_potUQ_electra'] = Cln_potUQ_electra
negation['Cln_potUQ_roberta'] = Cln_potUQ_roberta
negation['Cln_potUQ_sgnet'] = Cln_potUQ_sgnet
negation['Cln_potUQ_retro'] = Cln_potUQ_retro

# Specify the desired column order
new_column_order = [
    'Question_Id', 'Context', 'Original_Question', 'Original_Answer',
       'Modified_Question', 'O-Q model2 answer span', 'Cln_orgQ_model2',
       'O-Q model2 start', 'O-Q model2 end', 'O-Q model2 score',
       'O-Q model4 answer span', 'Cln_orgQ_model4', 'O-Q model4 start', 'O-Q model4 end',
       'O-Q model4 score', 'O-Q electra answer span','Cln_orgQ_electra', 'O-Q electra start',
       'O-Q electra end', 'O-Q electra score', 'O-Q roberta answer span', 'Cln_orgQ_roberta',
       'O-Q roberta start', 'O-Q roberta end', 'O-Q roberta score',
       'O-Q sgnet answer span', 'Cln_orgQ_sgnet' ,'O-Q retro answer span', 'Cln_orgQ_retro',
       'P-U model2 answer span', 'Cln_potUQ_model2', 'P-U model2 start', 'P-U model2 end',
       'P-U model2 score', 'P-U model4 answer span', 'Cln_potUQ_model4', 'P-U model4 start',
       'P-U model4 end', 'P-U model4 score', 'P-U electra answer span', 'Cln_potUQ_electra',
       'P-U electra start', 'P-U electra end', 'P-U electra score',
       'P-U roberta answer span', 'Cln_potUQ_roberta', 'P-U roberta start', 'P-U roberta end',
       'P-U roberta score', 'P-U SgNet answer span', 'Cln_potUQ_sgnet', 'P-U retro answer span', 'Cln_potUQ_retro'
    
]



       
# Reorder the columns in the DataFrame
negation = negation[new_column_order]


negation

0
100000

,Question_Id,Context,Original_Question,Original_Answer,Modified_Question,O-Q model2 answer span,Cln_orgQ_model2,O-Q model2 start,O-Q model2 end,O-Q model2 score,...,P-U electra score,P-U roberta answer span,Cln_potUQ_roberta,P-U roberta start,P-U roberta end,P-U roberta score,P-U SgNet answer span,Cln_potUQ_sgnet,P-U retro answer span,Cln_potUQ_retro
0,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When didn't Beyonce start becoming popular?,late 1990s,late 1990s,275,286,0.636688,...,3.663901e-12,4,4,74,75,2.375909e-09,the late 1990s as,the late 1990s as,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
1,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce not start becoming popular?,late 1990s,late 1990s,275,286,0.636688,...,3.835370e-11,4,4,74,75,1.432447e-09,the late 1990s as,the late 1990s as,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
2,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce start not becoming popular?,late 1990s,late 1990s,275,286,0.636688,...,5.543973e-05,2003,2003,526,530,2.668854e-09,the late 1990s as,the late 1990s as,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
3,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas didn't Beyonce compete in when she ...,singing and dancing,singing and dancing,206,226,0.836062,...,7.576573e-12,Beyoncé Giselle Knowles-Carter,Beyoncé Giselle Knowles-Carter,0,30,2.841676e-09,NaN,,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
4,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas did Beyonce compete in when she was...,singing and dancing,singing and dancing,206,226,0.836062,...,2.723598e-07,singing and dancing competitions,singing and dancing competitions,207,239,1.565185e-06,NaN,,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162180,5735d259012e2f140011a09f,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,Minsk,With what Belorussian city doesn't Kathmandu h...,Minsk,Minsk,475,481,0.972188,...,3.207862e-09,Minsk,Minsk,476,481,5.784440e-09,NaN,,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
162181,5735d259012e2f140011a09f,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,Minsk,With what Belorussian city does Kathmandu not ...,Minsk,Minsk,475,481,0.972188,...,1.300888e-08,Minsk,Minsk,476,481,1.215596e-07,NaN,,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
162182,5735d259012e2f140011a0a0,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,1975,In what year didn't Kathmandu create its initi...,1975,1975,198,203,0.996814,...,3.486395e-12,1975,1975,199,203,8.635733e-11,NaN,,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
162183,5735d259012e2f140011a0a0,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,1975,In what year did Kathmandu not create its init...,1975,1975,198,203,0.996814,...,9.288781e-13,1975,1975,199,203,1.607741e-10,NaN,,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...
162184,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,What isn't KMC an initialism of?,Kathmandu Metropolitan City,Kathmandu Metropolitan City,0,27,0.949815,...,3.328238e-14,Motsumoto City of Japan,Motsumoto City of Japan,350,373,5.829913e-11,empty,empty,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...

 # EM and unanswerability

In [6]:

EM_dataset_Cln_orgQ_model2 = []
EM_dataset_Cln_orgQ_model4 = []
EM_dataset_Cln_orgQ_electra = []
EM_dataset_Cln_orgQ_roberta = []
EM_dataset_Cln_orgQ_sgnet = []
EM_dataset_Cln_orgQ_retro = []

EM_dataset_Cln_potUQ_model2 = []
EM_dataset_Cln_potUQ_model4 = []
EM_dataset_Cln_potUQ_electra = []
EM_dataset_Cln_potUQ_roberta = []
Null_EM_dataset_Cln_potUQ_sgnet = []
Null_EM_dataset_Cln_potUQ_retro = []
### for unanswerability
un_potUQ_model2 = []
un_potUQ_model4 = []
un_potUQ_electra = []
un_potUQ_roberta = []
un_potUQ_sgnet = []
un_potUQ_retro = []


for index, row in negation.iterrows():
    if index % 100000 == 0:
        print(index)
        
    original_answer_in_dataset = row['Original_Answer']

    original_question_model2 = row['Cln_orgQ_model2']
    original_question_model4 = row['Cln_orgQ_model4']
    original_question_electra = row['Cln_orgQ_electra']
    original_question_roberta = row['Cln_orgQ_roberta']
    original_question_sgnet = row['Cln_orgQ_sgnet']
    original_question_retro = row['Cln_orgQ_retro']
    

    potentialU_question_sgnet = row['Cln_potUQ_sgnet']
    potentialU_question_retro = row['Cln_potUQ_retro']
    potentialU_questionS_model2 = row['P-U model2 score']
    potentialU_questionS_model4 = row['P-U model4 score']
    potentialU_questionS_electra = row['P-U electra score']
    potentialU_questionS_roberta = row['P-U roberta score']
    



    if original_answer_in_dataset == original_question_model2:  # EM checking (dataset , model on org_q)
        EM_dataset_Cln_orgQ_model2.append(1)
    else:
        EM_dataset_Cln_orgQ_model2.append(0)
    
    if original_answer_in_dataset == original_question_model4:
        EM_dataset_Cln_orgQ_model4.append(1)
    else:
        EM_dataset_Cln_orgQ_model4.append(0)
    
    if original_answer_in_dataset == original_question_electra:
        EM_dataset_Cln_orgQ_electra.append(1)
    else:
        EM_dataset_Cln_orgQ_electra.append(0)
        
    if original_answer_in_dataset == original_question_roberta:
        EM_dataset_Cln_orgQ_roberta.append(1)
    else:
        EM_dataset_Cln_orgQ_roberta.append(0)
    
    if original_answer_in_dataset == original_question_sgnet:
        EM_dataset_Cln_orgQ_sgnet.append(1)
    else:
        EM_dataset_Cln_orgQ_sgnet.append(0)
        
    if original_answer_in_dataset == original_question_retro:
        EM_dataset_Cln_orgQ_retro.append(1)
    else:
        EM_dataset_Cln_orgQ_retro.append(0)
        
    if original_answer_in_dataset == potentialU_question_model2: ## EM checking (dataset, model on p-u_q)
        EM_dataset_Cln_potUQ_model2.append(1)
    else:
        EM_dataset_Cln_potUQ_model2.append(0)
    
    if original_answer_in_dataset == potentialU_question_model4:
        EM_dataset_Cln_potUQ_model4.append(1)
    else:
        EM_dataset_Cln_potUQ_model4.append(0)
    
    if original_answer_in_dataset == potentialU_question_electra:
        EM_dataset_Cln_potUQ_electra.append(1)
    else:
        EM_dataset_Cln_potUQ_electra.append(0)
        
    if original_answer_in_dataset == potentialU_question_roberta:
        EM_dataset_Cln_potUQ_roberta.append(1)
    else:
        EM_dataset_Cln_potUQ_roberta.append(0)
    
    Null_EM_dataset_Cln_potUQ_sgnet.append(100)
    Null_EM_dataset_Cln_potUQ_retro.append(100)

    if potentialU_questionS_model2 <= 0.096476303 : # unanswerablity checking
        un_potUQ_model2.append(0)  #unanswerable
    else:
        un_potUQ_model2.append(1)  #answerable
    
    if potentialU_questionS_model4 <= 0.15272566:
        un_potUQ_model4.append(0) #unanswerable
    else:
        un_potUQ_model4.append(1) #answerable
    
    if potentialU_questionS_electra <= 0.141489303:
        un_potUQ_electra.append(0) #unanswerable
    else:
        un_potUQ_electra.append(1) #answerable
        
    if potentialU_questionS_roberta <= 0.063691394:
        un_potUQ_roberta.append(0) #unanswerable
    else: 
        un_potUQ_roberta.append(1) #answerable
    
    if potentialU_question_sgnet == "": 
        un_potUQ_sgnet.append(0) #unanswerable
    else:
        un_potUQ_sgnet.append(1) #answerable
        
    if potentialU_question_retro == "" or potentialU_question_retro.startswith("[SEP]") or potentialU_question_retro == "'" or potentialU_question_retro == "," or potentialU_question_retro == "<No Answer>. The question is not answerable according to the context." or potentialU_question_retro == "<unk>=0" :
        un_potUQ_retro.append(0) #unanswerable
    else:
        un_potUQ_retro.append(1) #answerable
        
negation['EM dataset with clean orgQ_model2'] = EM_dataset_Cln_orgQ_model2
negation['EM dataset with clean orgQ_model4'] = EM_dataset_Cln_orgQ_model4
negation['EM dataset with clean orgQ_electra'] = EM_dataset_Cln_orgQ_electra
negation['EM dataset with clean orgQ_roberta'] = EM_dataset_Cln_orgQ_roberta
negation['EM dataset with clean orgQ_sgnet'] = EM_dataset_Cln_orgQ_sgnet
negation['EM dataset with clean orgQ_retro'] = EM_dataset_Cln_orgQ_retro


negation['EM dataset with clean potentailUQ_model2'] = EM_dataset_Cln_potUQ_model2
negation['EM dataset with clean potentailUQ_model4'] = EM_dataset_Cln_potUQ_model4
negation['EM dataset with clean potentailUQ_electra'] = EM_dataset_Cln_potUQ_electra
negation['EM dataset with clean potentailUQ_roberta'] = EM_dataset_Cln_potUQ_roberta
negation['NULL EM dataset with clean potentailUQ_sgnet'] = Null_EM_dataset_Cln_potUQ_sgnet
negation['NULL EM dataset with clean potentailUQ_retro'] = Null_EM_dataset_Cln_potUQ_retro


negation['unanswerability potentailUQ_model2'] = un_potUQ_model2
negation['unanswerability potentailUQ_model4'] = un_potUQ_model4
negation['unanswerability potentailUQ_electra'] = un_potUQ_electra
negation['unanswerability potentailUQ_roberta'] = un_potUQ_roberta
negation['unanswerability potentailUQ_sgnet'] = un_potUQ_sgnet
negation['unanswerability potentailUQ_retro'] = un_potUQ_retro

new_column_order = [
    'Question_Id', 'Context', 'Original_Question', 'Original_Answer',
    'Modified_Question', 'O-Q model2 answer span', 'Cln_orgQ_model2', 'EM dataset with clean orgQ_model2',
    'O-Q model2 start', 'O-Q model2 end', 'O-Q model2 score',
    'O-Q model4 answer span', 'Cln_orgQ_model4','EM dataset with clean orgQ_model4' ,'O-Q model4 start', 'O-Q model4 end',
    'O-Q model4 score', 'O-Q electra answer span','Cln_orgQ_electra', 'EM dataset with clean orgQ_electra', 'O-Q electra start',
    'O-Q electra end', 'O-Q electra score', 'O-Q roberta answer span', 'Cln_orgQ_roberta', 'EM dataset with clean orgQ_roberta',
    'O-Q roberta start', 'O-Q roberta end', 'O-Q roberta score',
    'O-Q sgnet answer span', 'Cln_orgQ_sgnet', 'EM dataset with clean orgQ_sgnet' ,'O-Q retro answer span', 'Cln_orgQ_retro', 'EM dataset with clean orgQ_retro',
    'P-U model2 answer span', 'Cln_potUQ_model2','EM dataset with clean potentailUQ_model2','unanswerability potentailUQ_model2' ,'P-U model2 start', 'P-U model2 end',
    'P-U model2 score', 'P-U model4 answer span', 'Cln_potUQ_model4','EM dataset with clean potentailUQ_model4','unanswerability potentailUQ_model4', 'P-U model4 start',
    'P-U model4 end', 'P-U model4 score', 'P-U electra answer span', 'Cln_potUQ_electra', 'EM dataset with clean potentailUQ_electra','unanswerability potentailUQ_electra',
    'P-U electra start', 'P-U electra end', 'P-U electra score',
    'P-U roberta answer span', 'Cln_potUQ_roberta','EM dataset with clean potentailUQ_roberta','unanswerability potentailUQ_roberta' ,'P-U roberta start', 'P-U roberta end',
    'P-U roberta score', 'P-U SgNet answer span', 'Cln_potUQ_sgnet','NULL EM dataset with clean potentailUQ_sgnet' ,'unanswerability potentailUQ_sgnet','P-U retro answer span', 'Cln_potUQ_retro',
    'NULL EM dataset with clean potentailUQ_retro', 'unanswerability potentailUQ_retro'
    
]



# Reorder the columns in the DataFrame
negation = negation[new_column_order]


negation

0
100000

/tmp/ipykernel_1622476/3247661948.py:133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean orgQ_model2'] = EM_dataset_Cln_orgQ_model2
/tmp/ipykernel_1622476/3247661948.py:134: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean orgQ_model4'] = EM_dataset_Cln_orgQ_model4
/tmp/ipykernel_1622476/3247661948.py:135: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean orgQ_electra'] = EM_dataset_Cln_orgQ_electra
/tmp/ipykernel_1622476/3247661948.py:136: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean orgQ_roberta'] = EM_dataset_Cln_orgQ_roberta
/tmp/ipykernel_1622476/3247661948.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean orgQ_sgnet'] = EM_dataset_Cln_orgQ_sgnet
/tmp/ipykernel_1622476/3247661948.py:138: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean orgQ_retro'] = EM_dataset_Cln_orgQ_retro
/tmp/ipykernel_1622476/3247661948.py:141: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean potentailUQ_model2'] = EM_dataset_Cln_potUQ_model2
/tmp/ipykernel_1622476/3247661948.py:142: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean potentailUQ_model4'] = EM_dataset_Cln_potUQ_model4
/tmp/ipykernel_1622476/3247661948.py:143: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean potentailUQ_electra'] = EM_dataset_Cln_potUQ_electra
/tmp/ipykernel_1622476/3247661948.py:144: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['EM dataset with clean potentailUQ_roberta'] = EM_dataset_Cln_potUQ_roberta
/tmp/ipykernel_1622476/3247661948.py:145: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['NULL EM dataset with clean potentailUQ_sgnet'] = Null_EM_dataset_Cln_potUQ_sgnet
/tmp/ipykernel_1622476/3247661948.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['NULL EM dataset with clean potentailUQ_retro'] = Null_EM_dataset_Cln_potUQ_retro
/tmp/ipykernel_1622476/3247661948.py:149: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['unanswerability potentailUQ_model2'] = un_potUQ_model2
/tmp/ipykernel_1622476/3247661948.py:150: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['unanswerability potentailUQ_model4'] = un_potUQ_model4
/tmp/ipykernel_1622476/3247661948.py:151: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['unanswerability potentailUQ_electra'] = un_potUQ_electra
/tmp/ipykernel_1622476/3247661948.py:152: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['unanswerability potentailUQ_roberta'] = un_potUQ_roberta
/tmp/ipykernel_1622476/3247661948.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['unanswerability potentailUQ_sgnet'] = un_potUQ_sgnet
/tmp/ipykernel_1622476/3247661948.py:154: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  negation['unanswerability potentailUQ_retro'] = un_potUQ_retro

,Question_Id,Context,Original_Question,Original_Answer,Modified_Question,O-Q model2 answer span,Cln_orgQ_model2,EM dataset with clean orgQ_model2,O-Q model2 start,O-Q model2 end,...,P-U roberta end,P-U roberta score,P-U SgNet answer span,Cln_potUQ_sgnet,NULL EM dataset with clean potentailUQ_sgnet,unanswerability potentailUQ_sgnet,P-U retro answer span,Cln_potUQ_retro,NULL EM dataset with clean potentailUQ_retro,unanswerability potentailUQ_retro
0,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When didn't Beyonce start becoming popular?,late 1990s,late 1990s,0,275,286,...,75,2.375909e-09,the late 1990s as,the late 1990s as,100,1,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
1,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce not start becoming popular?,late 1990s,late 1990s,0,275,286,...,75,1.432447e-09,the late 1990s as,the late 1990s as,100,1,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
2,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce start not becoming popular?,late 1990s,late 1990s,0,275,286,...,530,2.668854e-09,the late 1990s as,the late 1990s as,100,1,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
3,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas didn't Beyonce compete in when she ...,singing and dancing,singing and dancing,0,206,226,...,30,2.841676e-09,NaN,,100,0,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
4,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas did Beyonce compete in when she was...,singing and dancing,singing and dancing,0,206,226,...,239,1.565185e-06,NaN,,100,0,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162180,5735d259012e2f140011a09f,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,Minsk,With what Belorussian city doesn't Kathmandu h...,Minsk,Minsk,0,475,481,...,481,5.784440e-09,NaN,,100,0,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
162181,5735d259012e2f140011a09f,"Kathmandu Metropolitan City (KMC), in order to...",With what Belorussian city does Kathmandu have...,Minsk,With what Belorussian city does Kathmandu not ...,Minsk,Minsk,0,475,481,...,481,1.215596e-07,NaN,,100,0,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
162182,5735d259012e2f140011a0a0,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,1975,In what year didn't Kathmandu create its initi...,1975,1975,1,198,203,...,203,8.635733e-11,NaN,,100,0,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
162183,5735d259012e2f140011a0a0,"Kathmandu Metropolitan City (KMC), in order to...",In what year did Kathmandu create its initial ...,1975,In what year did Kathmandu not create its init...,1975,1975,1,198,203,...,203,1.607741e-10,NaN,,100,0,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0
162184,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,What isn't KMC an initialism of?,Kathmandu Metropolitan City,Kathmandu Metropolitan City,1,0,27,...,373,5.829913e-11,empty,empty,100,1,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,100,0

# Working on EM results

In [7]:
import pandas as pd
from tqdm import tqdm

# Define an empty list to hold the rows
rows = []

# Iterate through the DataFrame using iterrows
for index, row in tqdm(negation.iterrows(), total=negation.shape[0], desc="Processing rows"):
    if index % 100000 == 0: 
        print(index)

    qid = row['Question_Id']
    context = row['Context']
    org_question = row['Original_Question']
    org_answer = row['Original_Answer']
    pu_question = row['Modified_Question']

    model_data = [
        ('model 2', row['Cln_orgQ_model2'], row['Cln_potUQ_model2'], row['EM dataset with clean orgQ_model2'], row['EM dataset with clean potentailUQ_model2'],row['unanswerability potentailUQ_model2']),
        ('model 4', row['Cln_orgQ_model4'], row['Cln_potUQ_model4'], row['EM dataset with clean orgQ_model4'], row['EM dataset with clean potentailUQ_model4'],row['unanswerability potentailUQ_model4']),
        ('electra', row['Cln_orgQ_electra'], row['Cln_potUQ_electra'], row['EM dataset with clean orgQ_electra'], row['EM dataset with clean potentailUQ_electra'],row['unanswerability potentailUQ_electra']),
        ('roberta', row['Cln_orgQ_roberta'], row['Cln_potUQ_roberta'], row['EM dataset with clean orgQ_roberta'], row['EM dataset with clean potentailUQ_roberta'],row['unanswerability potentailUQ_roberta']),
        ('sgnet', row['Cln_orgQ_sgnet'], row['Cln_potUQ_sgnet'], row['EM dataset with clean orgQ_sgnet'], row['NULL EM dataset with clean potentailUQ_sgnet'],row['unanswerability potentailUQ_sgnet']),
        ('retro', row['Cln_orgQ_retro'], row['Cln_potUQ_retro'], row['EM dataset with clean orgQ_retro'], row['NULL EM dataset with clean potentailUQ_retro'],row['unanswerability potentailUQ_retro'])
    ]

    for model_name, org_output, pu_output, org_em, pu_em,un in model_data:
        row_data = [qid, context, org_question, org_answer, org_output, pu_question, pu_output, org_em, pu_em,un, model_name]
        rows.append(row_data)

# Convert the list of rows to a DataFrame
result_df = pd.DataFrame(rows, columns=['qid', 'context', 'original question in dataset', 'original answer span in dataset', 
                                        'output of model for original question', 'potentail_UQ question', 
                                        'output of model for potentail_UQ question', 
                                        'EM-dataset answer with model on orgQ', 'EM-dataset answer with model on potentialUQ', 'unanswerability on potential question',
                                        'model name'])

result_df

Processing rows:   2%|▉                                                         | 2790/162185 [00:00<00:20, 7961.00it/s]

0

Processing rows:  63%|██████████████████████████████████▊                    | 102621/162185 [00:08<00:04, 12388.06it/s]

100000

Processing rows: 100%|███████████████████████████████████████████████████████| 162185/162185 [00:12<00:00, 12497.00it/s]

,qid,context,original question in dataset,original answer span in dataset,output of model for original question,potentail_UQ question,output of model for potentail_UQ question,EM-dataset answer with model on orgQ,EM-dataset answer with model on potentialUQ,unanswerability on potential question,model name
0,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,late 1990s,When didn't Beyonce start becoming popular?,"(2003),",0,0,0,model 2
1,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,late 1990s,When didn't Beyonce start becoming popular?,1990,0,0,0,model 4
2,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,in the late 1990s,When didn't Beyonce start becoming popular?,hiatus saw the release of Beyoncé's debut albu...,1,0,0,electra
3,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,late 1990s,When didn't Beyonce start becoming popular?,4,0,0,0,roberta
4,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,in,When didn't Beyonce start becoming popular?,the late 1990s as,0,100,1,sgnet
...,...,...,...,...,...,...,...,...,...,...,...
973105,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,Kathmandu,What isn't KMC an initialism of?,Kathmandu.,0,0,0,model 4
973106,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,Secretariat,What isn't KMC an initialism of?,IRC,0,0,0,electra
973107,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,Kathmandu Metropolitan City,What isn't KMC an initialism of?,Motsumoto City of Japan,1,0,0,roberta
973108,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,,What isn't KMC an initialism of?,empty,0,100,1,sgnet
973109,5735d259012e2f140011a0a1,"Kathmandu Metropolitan City (KMC), in order to...",What is KMC an initialism of?,Kathmandu Metropolitan City,kathmandu metropolitan city,What isn't KMC an initialism of?,<No Answer>. The question is not answerable ac...,0,100,0,retro

In [8]:
result_df.to_csv('20240704-forAllConditions_Negation_Eval100.csv')
# result_df = pd.read_csv("20240624-forAllConditions_Negation_NEW-EVAL.csv",sep=',')
# modified_Entity_Swap_df
print('percentages over all models')
model_name_counts = result_df['model name'].value_counts()
print(model_name_counts)
print("total row = " , len(result_df['model name']))

percentages over all models
model name
model 2    162185
model 4    162185
electra    162185
roberta    162185
sgnet      162185
retro      162185
Name: count, dtype: int64
total row =  973110

In [9]:
import pandas as pd

# Group by 'qid' and 'potential_UQ question'
grouped = result_df.groupby(['qid', 'potentail_UQ question'])

# Initialize an empty list to hold the result
result_list = []

# Iterate over each group
for name, group in grouped:
    model_name_list = []
    sw = True
    qid, potential_UQ_question = name  # unpack the group name
    
    # Assume that context, original_question, and original_answer_span are the same for each group
    context = group.iloc[0]['context']
    original_question = group.iloc[0]['original question in dataset']
    original_answer_span = group.iloc[0]['original answer span in dataset']
    
    # Iterate through each row in the group
    for index, row in group.iterrows():
        EM_orgQ = row['EM-dataset answer with model on orgQ']
        EM_modifiedQ = row['EM-dataset answer with model on potentialUQ']
        unanswerability = row['unanswerability on potential question']
        
        #### New eval (1,0,0) for model2,model4,electra,roberta AND (1,0) for retro and sgnet   
        model_n = row['model name']
        if EM_orgQ ==1 : ### originalQ should be answered
            if model_n == 'model 2' or model_n == 'model 4' or model_n == 'electra' or model_n == 'roberta': 
                if EM_modifiedQ == 0 and unanswerability == 0:  ## if model couldn't answer it (low score , and em=0 for p-u), now let's consider this model
                    if row['model name'] not in model_name_list:
                        model_name_list.append(row['model name'])
            elif model_n == 'retro' or model_n == 'sgnet':
                if unanswerability == 0:  ## if model couldn't answer it (null or empty answer), now let's consider this model
                    if row['model name'] not in model_name_list:
                        model_name_list.append(row['model name'])
    
    # Add the result to the list
    result_list.append({
        'qid': qid,
        'context': context,
        'original_question': original_question,
        'original_answer_span': original_answer_span,
        'potential_UQ_question': potential_UQ_question,
        'model_name_list': model_name_list,
        'len': len(model_name_list)
    })

# Create a new DataFrame from the result list
new_df = pd.DataFrame(result_list)
new_df.to_csv('20240704-for10Conditions_Negation_EVAL100.csv')
# Display the new DataFrame
display(new_df)

,qid,context,original_question,original_answer_span,potential_UQ_question,model_name_list,len
0,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce not start becoming popular?,[electra],1
1,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When did Beyonce start not becoming popular?,[electra],1
2,56be85543aeaaa14008c9063,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When did Beyonce start becoming popular?,in the late 1990s,When didn't Beyonce start becoming popular?,[electra],1
3,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas did Beyonce compete in when she was...,"[roberta, retro]",2
4,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas did Beyonce compete in when she was...,"[electra, roberta, retro]",3
...,...,...,...,...,...,...,...
161162,573636bf9c79961900ff7e08,"In contrast, Botswana has recently been forced...",What animal numbers have increased in Botswana?,hippopotamus,What animal numbers have not increased in Bots...,"[model 4, roberta, retro]",3
161163,573636bf9c79961900ff7e09,"In contrast, Botswana has recently been forced...",What animal numbers remain stable in Botswana?,elephant,What animal numbers remain not stable in Botsw...,"[electra, roberta, retro]",3
161164,573636bf9c79961900ff7e0a,"In contrast, Botswana has recently been forced...",What else is partly to blame for the declining...,poaching,What else is partly to blame for the not decli...,[electra],1
161165,573636bf9c79961900ff7e0a,"In contrast, Botswana has recently been forced...",What else is partly to blame for the declining...,poaching,What else is partly to not blame for the decli...,[electra],1
161166,573636bf9c79961900ff7e0a,"In contrast, Botswana has recently been forced...",What else is partly to blame for the declining...,poaching,What else isn't partly to blame for the declin...,[electra],1

In [13]:
filtered_df = new_df[new_df['len'] >= 4]
filtered_df.to_csv('20240704-Negation-FinalUQ-EVAL100.csv')
filtered_df

,qid,context,original_question,original_answer_span,potential_UQ_question,model_name_list,len
5,56be85543aeaaa14008c9065,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,What areas did Beyonce compete in when she was...,singing and dancing,What areas didn't Beyonce compete in when she ...,"[model 4, electra, roberta, retro]",4
9,56be86cf3aeaaa14008c9076,Following the disbandment of Destiny's Child i...,"After her second solo album, what other entert...",acting,"After her second solo album, what other entert...","[model 4, electra, roberta, retro]",4
13,56be86cf3aeaaa14008c9079,Following the disbandment of Destiny's Child i...,"To set the record for Grammys, how many did Be...",six,"To set the record for Grammys, how many didn't...","[model 4, electra, roberta, retro]",4
16,56be88473aeaaa14008c9083,"A self-described ""modern-day feminist"", Beyonc...",Time magazine named her one of the most 100 wh...,influential,Time magazine didn't name her one of the most ...,"[model 4, electra, roberta, retro]",4
19,56be892d3aeaaa14008c908c,"Beyoncé Giselle Knowles was born in Houston, T...",Where did Beyonce get her name from?,her mother's maiden name,Where did Beyonce not get her name from?,"[model 4, electra, roberta, retro]",4
...,...,...,...,...,...,...,...
161151,5736357e506b471400236597,The American bison is a large bovid which inha...,What part of North America did the bison live?,western,What part of North America didn't the bison live?,"[model 4, electra, roberta, retro]",4
161157,5736357e506b47140023659a,The American bison is a large bovid which inha...,What do bison still remain?,near-threatened,What don't bison still remain?,"[model 4, electra, roberta, retro]",4
161158,573636bf9c79961900ff7e06,"In contrast, Botswana has recently been forced...",What Botswana was resently forced to do?,ban trophy hunting,What Botswana was resently forced to don't?,"[model 4, electra, roberta, retro]",4
161159,573636bf9c79961900ff7e06,"In contrast, Botswana has recently been forced...",What Botswana was resently forced to do?,ban trophy hunting,What Botswana was resently not forced to do?,"[model 4, electra, roberta, retro]",4
161160,573636bf9c79961900ff7e06,"In contrast, Botswana has recently been forced...",What Botswana was resently forced to do?,ban trophy hunting,What Botswana wasn't resently forced to do?,"[model 4, electra, roberta, retro]",4

In [11]:
# Define the conditions you want to check
conditions = [
    ('len >= 1', new_df['len'] >= 1),
    ('len == 3', new_df['len'] == 3),
    ('len == 4', new_df['len'] == 4),
    ('len == 5', new_df['len'] == 5),
    ('len == 6', new_df['len'] == 6),
    ('len >= 3', new_df['len'] >= 3),
    ('len >= 4', new_df['len'] >= 4),
    ('len >= 5', new_df['len'] >= 5)
]

# Initialize an empty dictionary to hold the results
condition_counts = {}

# Iterate over each condition
for condition_name, condition in conditions:
    # Filter the DataFrame based on the current condition
    filtered_df = new_df[condition]
    
    # Count the number of records that meet the condition
    count = filtered_df.shape[0]
    
    # Store the count in the dictionary
    condition_counts[condition_name] = count

# Display the counts for each condition
for condition_name, count in condition_counts.items():
    print(f"Number of records where {condition_name}: {count}")

Number of records where len >= 1: 151371
Number of records where len == 3: 59394
Number of records where len == 4: 36691
Number of records where len == 5: 8360
Number of records where len == 6: 2
Number of records where len >= 3: 104447
Number of records where len >= 4: 45053
Number of records where len >= 5: 8362