In [13]:
'''import libraries used, json to read the data, 
randint for randomly generated paragraphs, 
and pandas to create a dataframe to be written to csv'''
import json
import pandas as pd
from random import randint
import spacy
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Opening JSON file, with specific file name
fname = 'train-SQuAD-v2.0'
f = open(fname + '.json')
#load in data as python dictionary using the json library
data = json.load(f)

In [14]:
doc = nlp("$118 million")
for ent in doc.ents:
    print(ent.label_)

MONEY

In [15]:
quickies = ["GPE", "LOC", "DATE"]
def generate_unanswerable_question(question, context, answer):
    con_sens = context.split(".")
    ans_section = ""
    for s in con_sens:
        if(answer in s):
            ans_section = s
    #print(question)
    questions = []
    doc = nlp(ans_section)
    entities = [ent.text for ent in doc.ents]
    labels = [ent.label_ for ent in doc.ents]
    etags = pos_tag(entities)
    qdoc = nlp(question)
    qents = [ent.text for ent in qdoc.ents]
    qlabels = [ent.label_ for ent in qdoc.ents]
    qtags = pos_tag(qents)
    adoc = nlp(answer)
    aents = [ent.text for ent in adoc.ents]
    alabels = [ent.label_ for ent in adoc.ents]
    if("DATE" in alabels):
        q = question.split(" ", 1)[1]
        questions.append("When on " + answer + " " + q)
    elif(("GPE" in alabels) or ("LOC" in alabels) or ("NORP" in alabels) or ("FAC" in alabels)):
        q = question.split(" ", 1)[1]
        questions.append("Where in " + answer + " " + q)
    elif(("PERSON" in alabels) or ("ORC" in alabels)):
        q = question.split(" ", 1)[1]
        questions.append("How did " + answer + " " + q)
    elif(("CARDINAL" in alabels) or ("ORDINAL" in alabels) or ("QUANTITY" in alabels)):
        q = question.split(" ", 2)[2]
        questions.append("What " + answer + " " + q)
    elif(("MONEY" in alabels) or ("PERCENT" in alabels)):
        if(len(question.split("the ")) > 1):
            q = question.replace("the ", "the distribution of the " + answer + " ")
        elif(len(question.split("much ")) > 1):
            q = question.split("much ")[1]
            q = "How was the " + answer + " distributed " + q
        else: 
            q = question.split(" ", 1)[1]
            q = "How was the " + answer + " distributed " + q
        questions.append(q)
        
    #entities_to_change = []
    #lentChange = []
    '''for i in range(0, len(qents)):
        for j in range(0, len(entities)):
            if(qlabels[i] == labels[j]):
                entities_to_change.append(qents[i])
                lentChange.append(qlabels[i])
    entities_to_change = list(set(entities_to_change))
    lentChange = list(set(lentChange))
    if("PERSON" not in alabels and "DATE" not in alabels and "GPE" not in alabels and "LOC" not in alabels and "CARDINAL" not in alabels):
        for i in range(0, len(entities_to_change)):
            questions.append(question.replace(entities_to_change[i], answer))'''
    return questions
    #print(aents)
    #print(alabels)
    #print(entities)
    #print(labels)
    #print(qents)
    #fent = qents[len(qents) - 1]
    #fent_tag = qtags[len(qents) - 1][1]
    #fentlabel = qlabels[len(qlabels) - 1]
    #adoc = nlp(answer)
    #aents = [ent.text for ent in adoc.ents]
    #print(qlabels)
        
#    return questions

'''    doc = nlp(text)
    entities = [ent.text for ent in doc.ents]

    for entity in entities:
        if entity not in exclude_list:
            question = text.replace(entity, "_______")
            return question

    return None'''

# Example text
question = "Who gave Chopin money in the last years of his life?"
answer = "Jane Stirling"
context = "At the age of 21 he settled in Paris. Thereafter, during the last 18 years of his life, he gave only some 30 public performances, preferring the more intimate atmosphere of the salon. He supported himself by selling his compositions and teaching piano, for which he was in high demand. Chopin formed a friendship with Franz Liszt and was admired by many of his musical contemporaries, including Robert Schumann. In 1835 he obtained French citizenship. After a failed engagement to Maria Wodzińska, from 1837 to 1847 he maintained an often troubled relationship with the French writer George Sand. A brief and unhappy visit to Majorca with Sand in 1838–39 was one of his most productive periods of composition. In his last years, he was financially supported by his admirer Jane Stirling, who also arranged for him to visit Scotland in 1848. Through most of his life, Chopin suffered from poor health. He died in Paris in 1849, probably of tuberculosis."
generate_unanswerable_question(question, context, answer)

question = "How much money did Apple have to pay to Creative as a result of their agreement?"
answer = "$100 million"
context = "On August 24, 2006, Apple and Creative announced a broad settlement to end their legal disputes. Apple will pay Creative US$100 million for a paid-up license, to use Creative's awarded patent in all Apple products. As part of the agreement, Apple will recoup part of its payment, if Creative is successful in licensing the patent. Creative then announced its intention to produce iPod accessories by joining the Made for iPod program."
print(generate_unanswerable_question(question, context, answer))

question = "What is the cost to build Cornell Tech?"
answer = "$2 Billion"
context = "The biotechnology sector is also growing in New York City, based upon the city's strength in academic scientific research and public and commercial financial support. On December 19, 2011, then Mayor Michael R. Bloomberg announced his choice of Cornell University and Technion-Israel Institute of Technology to build a US$2 billion graduate school of applied sciences called Cornell Tech on Roosevelt Island with the goal of transforming New York City into the world's premier technology capital. By mid-2014, Accelerator, a biotech investment firm, had raised more than US$30 million from investors, including Eli Lilly and Company, Pfizer, and Johnson & Johnson, for initial funding to create biotechnology startups at the Alexandria Center for Life Science, which encompasses more than 700,000 square feet (65,000 m2) on East 29th Street and promotes collaboration among scientists and entrepreneurs at the center and with nearby academic, medical, and research institutions. The New York City Economic Development Corporation's Early Stage Life Sciences Funding Initiative and venture capital partners, including Celgene, General Electric Ventures, and Eli Lilly, committed a minimum of US$100 million to help launch 15 to 20 ventures in life sciences and biotechnology."
print(generate_unanswerable_question(question, context, answer))

question = "What was the percentage increase of Manhattan hotel rooms between 2013 and 2014?"
answer = "10%"
context = "Manhattan was on track to have an estimated 90,000 hotel rooms at the end of 2014, a 10% increase from 2013. In October 2014, the Anbang Insurance Group, based in China, purchased the Waldorf Astoria New York for US$1.95 billion, making it the world's most expensive hotel ever sold."
print(generate_unanswerable_question(question, context, answer))

question = "How many Chopin pieces are known to have survived?"
answer = "over 230"
context = "Over 230 works of Chopin survive; some compositions from early childhood have been lost. All his known works involve the piano, and only a few range beyond solo piano music, as either piano concertos, songs or chamber music."
print(generate_unanswerable_question(question, context, answer))

['How was the $100 million distributed money did Apple have to pay to Creative as a result of their agreement?']
['What is the distribution of the $2 Billion cost to build Cornell Tech?']
['What was the distribution of the 10% percentage increase of Manhattan hotel rooms between 2013 and 2014?']
['What over 230 Chopin pieces are known to have survived?']

In [16]:
question = "How is Nirvana achieved?"
answer = "practicing the Noble Eightfold Path (also known as the Middle Way)"
context = "In Theravada Buddhism, the ultimate goal is the attainment of the sublime state of Nirvana, achieved by practicing the Noble Eightfold Path (also known as the Middle Way), thus escaping what is seen as a cycle of suffering and rebirth. Mahayana Buddhism instead aspires to Buddhahood via the bodhisattva path, a state wherein one remains in this cycle to help other beings reach awakening. Tibetan Buddhism aspires to Buddhahood or rainbow body"
# Generate unanswerable question
print(generate_unanswerable_question(question, context, answer))

question = "Where are more moist areas found in southern Europe?"
answer = "north coast of Spain"
context = "Cooler climates can be found in certain parts of Southern European countries, for example within the mountain ranges of Spain and Italy. Additionally, the north coast of Spain experiences a wetter Atlantic climate."
# Generate unanswerable question
print(generate_unanswerable_question(question, context, answer))

['Where in practicing the Noble Eightfold Path (also known as the Middle Way) is Nirvana achieved?']
['Where in north coast of Spain are more moist areas found in southern Europe?']

In [17]:
#access the data key in the dictionary for access to all question frameworks
data = data['data']

In [18]:
#this is the dataframe that will be converted to pandas and then to csv
final_df = []
counter = 0
#loop through all different data titles/topics associated!
for i in range(0, len(data)):
    #get number of paragraphs per topic
    length = len(data[i]['paragraphs'])
    #get list of all paragraphs for later use
    paragraphs = data[i]['paragraphs']
    #loop through each paragraph
    for j in range(0, len(paragraphs)):
        #get all of the questions associated per paragraph
        questions = paragraphs[j]['qas']
        #get the context paragraph value
        context = paragraphs[j]['context']
        #loop through all questions in each topic paragraph
        for k in range(0, len(questions)):
            if(questions[k]['is_impossible'] == False):
                #get the question id
                id = questions[k]['id']
                #get question value
                question = questions[k]['question']
                answer = questions[k]['answers'][0]['text']
                try:
                    un_questions = generate_unanswerable_question(question, context, answer)
                    for q in un_questions:
                        #add dictionary row value as per columns in instruction(assume modified is the same as original question, no description otherwise)
                        row = {"Question_Id": id, "Original_Question": question, "Original_Passage": context, "Modified_Question": q}
                        #add the row to the df list
                        final_df.append(row)
                except:
                    pass
                counter += 1
                if(counter%1000 == 0):
                    print(str(counter) + " out of: 131,000")
            else:
                pass

1000 out of: 131,000
2000 out of: 131,000
3000 out of: 131,000
4000 out of: 131,000
5000 out of: 131,000
6000 out of: 131,000
7000 out of: 131,000
8000 out of: 131,000
9000 out of: 131,000
10000 out of: 131,000
11000 out of: 131,000
12000 out of: 131,000
13000 out of: 131,000
14000 out of: 131,000
15000 out of: 131,000
16000 out of: 131,000
17000 out of: 131,000
18000 out of: 131,000
19000 out of: 131,000
20000 out of: 131,000
21000 out of: 131,000
22000 out of: 131,000
23000 out of: 131,000
24000 out of: 131,000
25000 out of: 131,000
26000 out of: 131,000
27000 out of: 131,000
28000 out of: 131,000
29000 out of: 131,000
30000 out of: 131,000
31000 out of: 131,000
32000 out of: 131,000
33000 out of: 131,000
34000 out of: 131,000
35000 out of: 131,000
36000 out of: 131,000
37000 out of: 131,000
38000 out of: 131,000
39000 out of: 131,000
40000 out of: 131,000
41000 out of: 131,000
42000 out of: 131,000
43000 out of: 131,000
44000 out of: 131,000
45000 out of: 131,000
46000 out of: 131,000
47000 out of: 131,000
48000 out of: 131,000
49000 out of: 131,000
50000 out of: 131,000
51000 out of: 131,000
52000 out of: 131,000
53000 out of: 131,000
54000 out of: 131,000
55000 out of: 131,000
56000 out of: 131,000
57000 out of: 131,000
58000 out of: 131,000
59000 out of: 131,000
60000 out of: 131,000
61000 out of: 131,000
62000 out of: 131,000
63000 out of: 131,000
64000 out of: 131,000
65000 out of: 131,000
66000 out of: 131,000
67000 out of: 131,000
68000 out of: 131,000
69000 out of: 131,000
70000 out of: 131,000
71000 out of: 131,000
72000 out of: 131,000
73000 out of: 131,000
74000 out of: 131,000
75000 out of: 131,000
76000 out of: 131,000
77000 out of: 131,000
78000 out of: 131,000
79000 out of: 131,000
80000 out of: 131,000
81000 out of: 131,000
82000 out of: 131,000
83000 out of: 131,000
84000 out of: 131,000
85000 out of: 131,000
86000 out of: 131,000

In [19]:
#create dataframe from the final_df list
final_df = pd.DataFrame(final_df)

In [20]:
#display this df to ensure correct outputs(seems good, original and new passages are different for each line)
final_df

,Question_Id,Original_Question,Original_Passage,Modified_Question
0,56be85543aeaaa14008c9063,When did Beyonce start becoming popular?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When on in the late 1990s did Beyonce start be...
1,56be85543aeaaa14008c9066,When did Beyonce leave Destiny's Child and bec...,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When on 2003 did Beyonce leave Destiny's Child...
2,56bf6b0f3aeaaa14008c9601,In what city and state did Beyonce grow up?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,"Where in Houston, Texas what city and state di..."
3,56bf6b0f3aeaaa14008c9602,In which decade did Beyonce become famous?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,When on late 1990s which decade did Beyonce be...
4,56bf6b0f3aeaaa14008c9605,Who managed the Destiny's Child group?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,How did Mathew Knowles managed the Destiny's C...
...,...,...,...,...
42702,5735d1a86c16ec1900b92833,How many airlines use Tribhuvan International ...,The main international airport serving Kathman...,What 22 airlines use Tribhuvan International f...
42703,5735d1a86c16ec1900b92834,From what city does Arkefly offer nonstop flig...,The main international airport serving Kathman...,Where in Amsterdam what city does Arkefly offe...
42704,5735d259012e2f140011a09d,In what US state did Kathmandu first establish...,"Kathmandu Metropolitan City (KMC), in order to...",Where in Oregon what US state did Kathmandu fi...
42705,5735d259012e2f140011a09f,With what Belorussian city does Kathmandu have...,"Kathmandu Metropolitan City (KMC), in order to...",Where in Minsk what Belorussian city does Kath...
42706,5735d259012e2f140011a0a0,In what year did Kathmandu create its initial ...,"Kathmandu Metropolitan City (KMC), in order to...",When on 1975 what year did Kathmandu create it...

In [21]:
#reset file name to client discretion
fname = "Mutual Exclusion"
#export df to csv, as per output format from instructions
final_df.to_csv(fname+ ".csv")